### PR TITLE
Adding new group structures

### PR DESCRIPTION
**Pull request by RLReed**
Adding several smaller structures from the CASMO suite, a large structure (~2000 groups), and an equal lethargy structure that uses ~500 thermal groups and equal lethargy above that to make a structure with any number of groups.

### CODE REVIEW

**Review by robertsj — CHANGES_REQUESTED** [review]
Nice contribution.  Just fix those print statements for py3.

**Comment by RLReed** [comment]
@robertsj The print statements were updated in d73bf0c

**Comment by RLReed** [comment]
@robertsj The group structures are now in the correct order.  Shem531 had to be removed because the source is in error.

**Comment by RLReed** [comment]
@robertsj Is this ready to merge?

**Comment by robertsj** [comment]
Yes, I think so.


________________________________

**Pull request merged**
